package com.zonelab.vmr.chat.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import lombok.Data;

import java.io.Serializable;

@Data
public class MessageId implements Serializable {
    private static final long serialVersionUID = 1L;

    @DynamoDBHashKey
    private ChatId chatId;

    @DynamoDBRangeKey
    @DynamoDBAutoGeneratedKey
    private String id;
}
